# Generated by Django 4.2.16 on 2025-04-22 05:49

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0026_delete_uploadedimage'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('news', '0002_rename_released_date_news_published_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('short_description', models.TextField(blank=True, null=True)),
                ('body', wagtail.fields.StreamField([('HtmlSourceBlock', 2), ('space', 4), ('ContentWithVariableWidthBlock', 24), ('TwoColumnBlock', 29), ('SliderGalleryBlock', 33), ('ContentWithImageAlignmentOption', 36), ('VideoBlock', 39)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'This label is for internal reference only and will not be displayed in the output.', 'required': False}), 1: ('wagtail.blocks.TextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('block_label', 0), ('source', 1)]], {}), 3: ('wagtail.blocks.IntegerBlock', (), {'default': 50}), 4: ('wagtail.blocks.StructBlock', [[('height', 3)]], {}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('col-lg-1', 'col-1'), ('col-lg-2', 'col-2'), ('col-lg-3', 'col-3'), ('col-lg-4', 'col-4'), ('col-lg-5', 'col-5'), ('col-lg-6', 'col-6'), ('col-lg-7', 'col-7'), ('col-lg-8', 'col-8'), ('col-lg-9', 'col-9'), ('col-lg-10', 'col-10'), ('col-lg-11', 'col-11'), ('col-lg-12', 'col-12')]}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('offset-lg-1', 'offset-1'), ('offset-lg-2', 'offset-2'), ('offset-lg-3', 'offset-3'), ('offset-lg-4', 'offset-4'), ('offset-lg-5', 'offset-5'), ('offset-lg-6', 'offset-6')], 'required': False}), 7: ('wagtail.blocks.RichTextBlock', (), {'features': ['H1', 'h2', 'h3', 'h4', 'h5', 'h6']}), 8: ('wagtail.blocks.CharBlock', (), {'required': False}), 9: ('wagtail.blocks.StructBlock', [[('heading', 7), ('css_class', 8)]], {}), 10: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('check-list', 'Checklist')], 'required': False}), 11: ('wagtail.blocks.RichTextBlock', (), {}), 12: ('wagtail.blocks.StructBlock', [[('list_style', 10), ('content', 11), ('css_class', 8)]], {}), 13: ('wagtail.blocks.CharBlock', (), {}), 14: ('wagtail.contrib.table_block.blocks.TableBlock', (), {}), 15: ('wagtail.blocks.StreamBlock', [[('table', 14)]], {}), 16: ('wagtail.blocks.CharBlock', (), {'help_text': 'Table container css class.', 'required': False}), 17: ('wagtail.blocks.StructBlock', [[('table_item', 15), ('css_class', 16)]], {}), 18: ('wagtail.blocks.StreamBlock', [[('html', 2), ('content', 12), ('heading', 9), ('space', 4), ('table', 17)]], {}), 19: ('wagtail.blocks.StructBlock', [[('title', 13), ('content_blocks', 18)]], {}), 20: ('wagtail.blocks.ListBlock', (19,), {}), 21: ('wagtail.blocks.StructBlock', [[('items', 20)]], {}), 22: ('wagtail.blocks.StructBlock', [[('quote', 1), ('author', 8)]], {}), 23: ('wagtail.blocks.StreamBlock', [[('html', 2), ('heading', 9), ('space', 4), ('content', 12), ('accordion', 21), ('QuoteBlock', 22), ('table', 17)]], {}), 24: ('wagtail.blocks.StructBlock', [[('column_width', 5), ('column_offset', 6), ('content_blocks', 23), ('css_class', 8)]], {}), 25: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('pt-0', 'No padding'), ('pt-1', '1x'), ('pt-2', '2x'), ('pt-3', '3x'), ('pt-4', '4x'), ('pt-5', '5x')], 'required': False}), 26: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('pb-0', 'No padding'), ('pb-1', '1x'), ('pb-2', '2x'), ('pb-3', '3x'), ('pb-4', '4x'), ('pb-5', '5x')], 'required': False}), 27: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('col-lg-1', 'col-1'), ('col-lg-2', 'col-2'), ('col-lg-3', 'col-3'), ('col-lg-4', 'col-4'), ('col-lg-5', 'col-5'), ('col-lg-6', 'col-6'), ('col-lg-7', 'col-7'), ('col-lg-8', 'col-8'), ('col-lg-9', 'col-9'), ('col-lg-10', 'col-10'), ('col-lg-11', 'col-11'), ('col-lg-12', 'col-12')], 'required': False}), 28: ('wagtail.blocks.StreamBlock', [[('html', 2), ('heading', 9), ('content', 12), ('space', 4), ('accordion', 21), ('quote', 22), ('table', 17)]], {}), 29: ('wagtail.blocks.StructBlock', [[('top_padding', 25), ('bottom_padding', 26), ('left_column_width', 27), ('left_column_offset', 6), ('left_column', 28), ('right_column_width', 27), ('right_column_offset', 6), ('right_column', 28), ('css_class', 8)]], {}), 30: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 31: ('wagtail.blocks.StructBlock', [[('image', 30), ('caption', 8)]], {}), 32: ('wagtail.blocks.ListBlock', (31,), {}), 33: ('wagtail.blocks.StructBlock', [[('items', 32)]], {}), 34: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left image with right content'), ('right', 'Left content with right image')]}), 35: ('wagtail.blocks.StreamBlock', [[('heading', 9), ('html', 2), ('content', 12)]], {}), 36: ('wagtail.blocks.StructBlock', [[('image', 30), ('alignment', 34), ('content', 35)]], {}), 37: ('wagtail.blocks.TextBlock', (), {'help_text': 'Enter the video URL'}), 38: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 39: ('wagtail.blocks.StructBlock', [[('video_url', 37), ('poster_image', 38)]], {})}, null=True)),
            ],
            options={
                'verbose_name': 'News Index Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RenameField(
            model_name='news',
            old_name='published_date',
            new_name='release_date',
        ),
        migrations.AddField(
            model_name='news',
            name='body',
            field=wagtail.fields.StreamField([], blank=True, block_lookup={}, null=True),
        ),
        migrations.CreateModel(
            name='NewspageHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('background_video_url', models.URLField(blank=True, help_text='mp4 video', null=True)),
                ('popup_video_url', models.URLField(blank=True, help_text='embeded video url', null=True)),
                ('button_label', models.CharField(blank=True, max_length=500, null=True)),
                ('button_url', models.URLField(blank=True, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='newspage_hero', to='news.newsindexpage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
