# Generated by Django 4.2.16 on 2025-10-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_newsindexpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspagehero',
            name='pre_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
