# Generated by Django 4.2.16 on 2025-10-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0030_alter_newsindexpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspagehero',
            name='popup_button_label',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
