# Generated by Django 4.2.16 on 2025-06-04 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('core', '0005_adminsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_url', models.URLField(blank=True, help_text='Enter the full Facebook profile or page URL.')),
                ('facebook_icon', models.CharField(blank=True, help_text='Font Awesome icon tag for Facebook (e.g. <i class="fab fa-facebook-f"></i>)', max_length=100)),
                ('twitter_url', models.URLField(blank=True, help_text='Enter the full Twitter/X profile URL.')),
                ('twitter_icon', models.CharField(blank=True, help_text='Font Awesome icon tag for Twitter (e.g. <i class="fab fa-x-twitter"></i>)', max_length=100)),
                ('youtube_url', models.URLField(blank=True, help_text='Enter the full YouTube channel or video URL.')),
                ('youtube_icon', models.CharField(blank=True, help_text='Font Awesome icon tag for YouTube (e.g. <i class="fab fa-youtube"></i>)', max_length=100)),
                ('linkedin_url', models.URLField(blank=True, help_text='Enter the full LinkedIn profile or company page URL.')),
                ('linkedin_icon', models.CharField(blank=True, help_text='Font Awesome icon tag for LinkedIn (e.g. <i class="fab fa-linkedin-in"></i>)', max_length=100)),
                ('instagram_url', models.URLField(blank=True, help_text='Enter the full Instagram profile URL.')),
                ('instagram_icon', models.CharField(blank=True, help_text='Font Awesome icon tag for Instagram (e.g. <i class="fab fa-instagram"></i>)', max_length=100)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Social Links',
                'verbose_name_plural': 'Social Links',
            },
        ),
    ]
