# Generated by Django 4.2.16 on 2025-05-19 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_alter_formpage_bottom_body_alter_formpage_top_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='autoresponder_email_field',
            field=models.BooleanField(default=False, verbose_name='Autoresponder email field'),
        ),
        migrations.AddField(
            model_name='formfield',
            name='autoresponder_first_name_field',
            field=models.BooleanField(default=False, verbose_name='Autoresponder first name field'),
        ),
        migrations.AddField(
            model_name='formfield',
            name='autoresponder_last_name_field',
            field=models.BooleanField(default=False, verbose_name='Autoresponder last name field'),
        ),
        migrations.AddField(
            model_name='formfield',
            name='autoresponder_salutation_field',
            field=models.BooleanField(default=False, verbose_name='Autoresponder salutation field'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='field_type',
            field=models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('multiselect', 'Multiple select'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time'), ('hidden', 'Hidden field'), ('image', 'Upload Image'), ('document', 'File Upload'), ('heading', 'Heading')], max_length=16, verbose_name='field type'),
        ),
    ]
