# Generated by Django 4.2.16 on 2025-10-03 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0026_delete_uploadedimage'),
        ('pages', '0024_alter_formpage_bottom_body_alter_formpage_top_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='canonical_url',
            field=models.URLField(blank=True, help_text="Leave blank to use the page's URL.", max_length=255, verbose_name='Canonical URL'),
        ),
        migrations.AddField(
            model_name='formpage',
            name='exclude_from_sitemap',
            field=models.BooleanField(default=False, help_text='If checked, this page will be excluded from sitemap.xml and not submitted to search engines.'),
        ),
        migrations.AddField(
            model_name='formpage',
            name='no_index',
            field=models.BooleanField(default=False, help_text="Check this to add a 'noindex' meta tag so search engines do not index this page."),
        ),
        migrations.AddField(
            model_name='formpage',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Shown when linking to this page on social media. If blank, may show an image from the page, or the default from Settings > SEO.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Preview image'),
        ),
        migrations.AddField(
            model_name='generalpage',
            name='canonical_url',
            field=models.URLField(blank=True, help_text="Leave blank to use the page's URL.", max_length=255, verbose_name='Canonical URL'),
        ),
        migrations.AddField(
            model_name='generalpage',
            name='exclude_from_sitemap',
            field=models.BooleanField(default=False, help_text='If checked, this page will be excluded from sitemap.xml and not submitted to search engines.'),
        ),
        migrations.AddField(
            model_name='generalpage',
            name='no_index',
            field=models.BooleanField(default=False, help_text="Check this to add a 'noindex' meta tag so search engines do not index this page."),
        ),
        migrations.AddField(
            model_name='generalpage',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Shown when linking to this page on social media. If blank, may show an image from the page, or the default from Settings > SEO.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Preview image'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='canonical_url',
            field=models.URLField(blank=True, help_text="Leave blank to use the page's URL.", max_length=255, verbose_name='Canonical URL'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='exclude_from_sitemap',
            field=models.BooleanField(default=False, help_text='If checked, this page will be excluded from sitemap.xml and not submitted to search engines.'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='no_index',
            field=models.BooleanField(default=False, help_text="Check this to add a 'noindex' meta tag so search engines do not index this page."),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Shown when linking to this page on social media. If blank, may show an image from the page, or the default from Settings > SEO.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Preview image'),
        ),
    ]
