# Generated by Django 4.2.16 on 2025-10-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_formpage_canonical_url_formpage_exclude_from_sitemap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='exclude_from_search',
            field=models.BooleanField(default=False, help_text='If checked, this page will be excluded from the site search results.'),
        ),
        migrations.AddField(
            model_name='generalpage',
            name='exclude_from_search',
            field=models.BooleanField(default=False, help_text='If checked, this page will be excluded from the site search results.'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='exclude_from_search',
            field=models.BooleanField(default=False, help_text='If checked, this page will be excluded from the site search results.'),
        ),
    ]
