# Generated by Django 4.2.16 on 2025-10-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_formpage_exclude_from_search_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalpagehero',
            name='pre_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='landingpagehero',
            name='pre_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
