# Generated by Django 4.2.16 on 2025-10-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0047_alter_formpage_bottom_body_alter_formpage_top_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalpagehero',
            name='popup_button_label',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='landingpagehero',
            name='popup_button_label',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
