# Generated by Django 4.2.16 on 2025-10-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0048_generalpagehero_popup_button_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalpagehero',
            name='popup_video_url',
            field=models.URLField(blank=True, help_text='embeded video url', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='landingpagehero',
            name='popup_video_url',
            field=models.URLField(blank=True, help_text='embeded video url', max_length=1000, null=True),
        ),
    ]
