# Generated by Django 5.2.7 on 2026-03-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0063_alter_formpage_bottom_body_alter_formpage_top_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalpage',
            name='hero_title_alignment',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center')], default='left', max_length=10),
        ),
    ]
