# Generated by Django 5.2.7 on 2026-03-02 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0065_landingpage_hero_section'),
        ('pages', '0066_alter_landingpage_body'),
    ]

    operations = [
    ]
