# Generated by Django 4.2.16 on 2026-03-03 00:00

from django.db import migrations


def remove_contact_pages_and_types(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Page = apps.get_model('wagtailcore', 'Page')

    contact_cts = list(ContentType.objects.filter(app_label='contact'))
    if not contact_cts:
        return

    contact_ct_ids = [ct.id for ct in contact_cts]

    # Delete pages individually to keep the tree consistent
    for page in Page.objects.filter(content_type_id__in=contact_ct_ids):
        page.delete()

    # Remove content types for the old contact app
    ContentType.objects.filter(app_label='contact').delete()


def drop_contact_tables(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    if vendor == 'postgresql':
        drop_suffix = ' CASCADE'
    else:
        drop_suffix = ''

    tables = [
        'contact_contactpagehero',
        'contact_contactpage',
        'contact_contactsubmission',
    ]
    for table in tables:
        schema_editor.execute(f'DROP TABLE IF EXISTS {table}{drop_suffix}')


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0067_merge_0065_landingpage_hero_section_0066_alter_landingpage_body'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RunPython(remove_contact_pages_and_types, migrations.RunPython.noop),
        migrations.RunPython(drop_contact_tables, migrations.RunPython.noop),
    ]
