# Generated by Django 4.2.16 on 2025-10-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_alter_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagehero',
            name='popup_button_label',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
