# Generated by Django 5.2.7 on 2026-02-28 12:38

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_homepage_hero_section_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_section',
            field=wagtail.fields.StreamField([('hero', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.ListBlock', (0,), {'help_text': "Each line animates in separately. Add one line per entry e.g. 'Let your' then 'light shine.'", 'label': 'Title lines'}), 2: ('wagtail.blocks.TextBlock', (), {'help_text': 'Paragraph text in the right column', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'required': False}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Background image / video poster frame', 'required': False}), 6: ('wagtail.blocks.URLBlock', (), {'help_text': 'MP4 video URL for hero background', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('title_lines', 1), ('text', 2), ('button_label', 3), ('button_url', 4), ('image', 5), ('background_video_url', 6)]], {})}, null=True),
        ),
    ]
